# coding: utf-8

from __future__ import absolute_import
from clashofcubicles.models.task_type import TaskType
from clashofcubicles.models.worker import Worker
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Office(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, workers=None, task_types=None):
        """
        Office - a model defined in Swagger

        :param id: The id of this Office.
        :type id: int
        :param workers: The workers of this Office.
        :type workers: List[Worker]
        :param task_types: The task_types of this Office.
        :type task_types: List[TaskType]
        """
        self.swagger_types = {
            'id': int,
            'workers': List[Worker],
            'task_types': List[TaskType]
        }

        self.attribute_map = {
            'id': 'id',
            'workers': 'workers',
            'task_types': 'taskTypes'
        }

        self._id = id
        self._workers = workers
        self._task_types = task_types

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Office of this Office.
        :rtype: Office
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self):
        """
        Gets the id of this Office.

        :return: The id of this Office.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Office.

        :param id: The id of this Office.
        :type id: int
        """

        self._id = id

    @property
    def workers(self):
        """
        Gets the workers of this Office.

        :return: The workers of this Office.
        :rtype: List[Worker]
        """
        return self._workers

    @workers.setter
    def workers(self, workers):
        """
        Sets the workers of this Office.

        :param workers: The workers of this Office.
        :type workers: List[Worker]
        """

        self._workers = workers

    @property
    def task_types(self):
        """
        Gets the task_types of this Office.

        :return: The task_types of this Office.
        :rtype: List[TaskType]
        """
        return self._task_types

    @task_types.setter
    def task_types(self, task_types):
        """
        Sets the task_types of this Office.

        :param task_types: The task_types of this Office.
        :type task_types: List[TaskType]
        """

        self._task_types = task_types

