# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class TaskType(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, description=None, setup_sgf=None):
        """
        TaskType - a model defined in Swagger

        :param id: The id of this TaskType.
        :type id: int
        :param description: The description of this TaskType.
        :type description: str
        :param setup_sgf: The setup_sgf of this TaskType.
        :type setup_sgf: str
        """
        self.swagger_types = {
            'id': int,
            'description': str,
            'setup_sgf': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'setup_sgf': 'setupSgf'
        }

        self._id = id
        self._description = description
        self._setup_sgf = setup_sgf

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskType of this TaskType.
        :rtype: TaskType
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self):
        """
        Gets the id of this TaskType.

        :return: The id of this TaskType.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TaskType.

        :param id: The id of this TaskType.
        :type id: int
        """

        self._id = id

    @property
    def description(self):
        """
        Gets the description of this TaskType.

        :return: The description of this TaskType.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this TaskType.

        :param description: The description of this TaskType.
        :type description: str
        """

        self._description = description

    @property
    def setup_sgf(self):
        """
        Gets the setup_sgf of this TaskType.

        :return: The setup_sgf of this TaskType.
        :rtype: str
        """
        return self._setup_sgf

    @setup_sgf.setter
    def setup_sgf(self, setup_sgf):
        """
        Sets the setup_sgf of this TaskType.

        :param setup_sgf: The setup_sgf of this TaskType.
        :type setup_sgf: str
        """

        self._setup_sgf = setup_sgf

